// src/core/orchestration/taskOrchestrationTypes.ts
// BOWCON V4.0 — MS-1.3.46: GOVERNED MULTI-AGENT TASK ORCHESTRATION & DISTRIBUTED EVIDENCE VERIFICATION
//
// Canonical type contracts, interfaces, and state machines for:
// - Governed multi-agent task orchestration
// - Parent/child task lifecycle management
// - Task dependency and sequencing control
// - Verifiable artifact handoffs
// - Cryptographic evidence aggregation
// - Evidence provenance and integrity verification
// - Partial/failed agent result reconciliation
// - Supervisor review before task completion
// - Cross-agent result contradiction detection
// - Safe orchestration recovery
//
// STRICT INVARIANTS:
// - MASTER_OWNER_AUTHORITY > BOW > BOWCON > PROJECTS
// - OWNER_DECISION > BOWCON_RECOMMENDATION
// - USER_STOP > EVERYTHING_AUTONOMOUS
// - REVOCATION > AGENT_INTENT
// - DELEGATION != AUTHORITY
// - DELEGATION != EXECUTION
// - CAPABILITY != AUTHORIZATION
// - AGENT != MASTER_OWNER
// - DEVICE != MASTER_OWNER
// - DEVICE_TRUST != EXECUTION_AUTHORITY
// - LEARNING != AUTHORIZATION
// - LEARNING != EXECUTION
// - PREDICTION != FACT
// - INFERENCE != FACT
// - MEMORY != TRUTH
// - EVIDENCE != AUTHORITY
// - VERIFICATION != AUTHORIZATION
// - TASK_COMPLETION != OWNER_APPROVAL
// - SUB_AGENT_RESULT != FACT
// - AGENT_COUNT != AUTHORITY_COUNT (No collective authority; consensus != authority)
// - C:\BOW\shopofbow: READS = 0, WRITES = 0, IMPORTS = 0, TOUCHES = 0

import {
  MASTER_OWNER_ID,
  AUTHORIZED_MASTER_OWNER_ALIASES,
  isMasterOwner,
} from '../architecture/masterArchitectureIdentity.js';
import type { DelegationScope } from '../delegation/delegationTypes.js';

export {
  MASTER_OWNER_ID,
  AUTHORIZED_MASTER_OWNER_ALIASES,
  isMasterOwner,
};

export const TASK_ORCHESTRATION_SCHEMA_VERSION = '4.0.0' as const;

/**
 * Unique identifiers
 */
export type TaskId = string;
export type TaskGroupId = string;

/**
 * Task execution lifecycle states.
 * INVARIANT: No semantic authority states exist here.
 */
export type TaskExecutionState =
  | 'PLANNED'
  | 'PENDING'
  | 'ASSIGNED'
  | 'READY'
  | 'RUNNING'
  | 'WAITING_DEPENDENCY'
  | 'BLOCKED'
  | 'PARTIAL'
  | 'SUCCEEDED'
  | 'FAILED'
  | 'CANCELLED'
  | 'INTERRUPTED'
  | 'VERIFICATION_PENDING'
  | 'VERIFIED'
  | 'REJECTED';

export const ALL_TASK_EXECUTION_STATES: readonly TaskExecutionState[] = Object.freeze([
  'PLANNED',
  'PENDING',
  'ASSIGNED',
  'READY',
  'RUNNING',
  'WAITING_DEPENDENCY',
  'BLOCKED',
  'PARTIAL',
  'SUCCEEDED',
  'FAILED',
  'CANCELLED',
  'INTERRUPTED',
  'VERIFICATION_PENDING',
  'VERIFIED',
  'REJECTED',
]);

/**
 * Task dependency relationship types.
 */
export type TaskDependencyType =
  | 'FINISH_TO_START'
  | 'REQUIRED_ARTIFACT'
  | 'STRICT_SUCCESS';

export interface TaskDependency {
  readonly dependentTaskId: TaskId;
  readonly type: TaskDependencyType;
  readonly requiredArtifactTypes?: readonly string[];
  readonly notes?: string;
}

/**
 * Task assignment record binding a task to an authorized, governed agent.
 */
export interface TaskAssignment {
  readonly assignmentId: string;
  readonly taskId: TaskId;
  readonly agentId: string;
  readonly deviceId: string;
  readonly delegationId: string;
  readonly sessionId: string;
  readonly assignedAt: number;
  readonly scope: DelegationScope;
  readonly leaseId?: string;
}

/**
 * Epistemic verification states for evidence records.
 */
export type EvidenceVerificationState =
  | 'OBSERVED'
  | 'UNVERIFIED'
  | 'VERIFIED'
  | 'REJECTED'
  | 'CONTRADICTED'
  | 'INCOMPLETE'
  | 'UNKNOWN';

export const ALL_EVIDENCE_VERIFICATION_STATES: readonly EvidenceVerificationState[] = Object.freeze([
  'OBSERVED',
  'UNVERIFIED',
  'VERIFIED',
  'REJECTED',
  'CONTRADICTED',
  'INCOMPLETE',
  'UNKNOWN',
]);

/**
 * Physical integrity status of evidence or artifact.
 */
export type EvidenceIntegrityStatus =
  | 'INTACT'
  | 'CORRUPTED'
  | 'HASH_MISMATCH'
  | 'MISSING_METADATA';

/**
 * Governed task artifact generated by an agent during task execution.
 * INVARIANT: Never persist credentials, tokens, or HumanGate approvals.
 */
export interface TaskArtifact {
  readonly artifactId: string;
  readonly taskId: TaskId;
  readonly agentId: string;
  readonly deviceId: string;
  readonly sessionId: string;
  readonly createdAt: number;
  readonly artifactType: string;
  readonly contentReference: string;
  readonly rawContent?: string;
  readonly contentHash: string; // SHA-256
  readonly provenance: readonly string[];
  readonly verificationState: EvidenceVerificationState;
  readonly metadata?: Readonly<Record<string, unknown>>;
}

/**
 * Lightweight reference to a verified or candidate artifact.
 */
export interface ArtifactReference {
  readonly artifactId: string;
  readonly contentHash: string;
  readonly artifactType: string;
}

/**
 * Cryptographic evidence record capturing verifiable execution outputs.
 * INVARIANT: EVIDENCE != AUTHORITY, SUB_AGENT_RESULT != FACT.
 */
export interface EvidenceRecord {
  readonly evidenceId: string;
  readonly taskId: TaskId;
  readonly artifactId?: string;
  readonly agentId: string;
  readonly deviceId: string;
  readonly sessionId: string;
  readonly observedAt: number;
  readonly integrityStatus: EvidenceIntegrityStatus;
  readonly verificationState: EvidenceVerificationState;
  readonly rawHash: string; // SHA-256 of the constituent artifact or result payload
  readonly provenance: readonly string[];
  readonly isSpeculative: boolean; // SUB_AGENT_RESULT != FACT
  readonly notes?: string;
}

/**
 * Epistemic state of an aggregated evidence bundle.
 */
export type EvidenceBundleEpistemicState =
  | 'EVIDENCE_OBSERVED'
  | 'EVIDENCE_VERIFIED'
  | 'EVIDENCE_CONTRADICTED'
  | 'EVIDENCE_INCOMPLETE'
  | 'EVIDENCE_REJECTED'
  | 'EVIDENCE_UNKNOWN';

/**
 * Aggregated cryptographic evidence bundle for a task or task group.
 * INVARIANT: Aggregation is NOT truth creation. Bundle remains evidence.
 */
export interface EvidenceBundle {
  readonly bundleId: string;
  readonly taskGroupId: TaskGroupId;
  readonly taskId?: TaskId;
  readonly sessionId: string;
  readonly evidenceList: readonly EvidenceRecord[];
  readonly totalCount: number;
  readonly verifiedCount: number;
  readonly rejectedCount: number;
  readonly contradictedCount: number;
  readonly incompleteCount: number;
  readonly bundleIntegrityHash: string; // Deterministic SHA-256 over sorted constituent hashes
  readonly epistemicState: EvidenceBundleEpistemicState;
  readonly createdAt: number;
}

/**
 * Verification evaluation outcome.
 */
export interface EvidenceVerificationResult {
  readonly verified: boolean;
  readonly status: EvidenceVerificationState;
  readonly integrityStatus: EvidenceIntegrityStatus;
  readonly errors: readonly string[];
  readonly contradictions?: readonly TaskContradiction[];
}

/**
 * Detailed outcome of an executed task.
 */
export interface TaskOutcome {
  readonly status: 'SUCCESS' | 'FAILURE' | 'PARTIAL' | 'BLOCKED' | 'INTERRUPTED';
  readonly summary: string;
  readonly outputData?: Readonly<Record<string, unknown>>;
  readonly artifacts: readonly TaskArtifact[];
  readonly completedAt: number;
  readonly durationMs: number;
}

/**
 * Governed result submitted by an agent upon task execution.
 * INVARIANT: isAdvisoryOnly is always true.
 */
export interface AgentTaskResult {
  readonly resultId: string;
  readonly taskId: TaskId;
  readonly agentId: string;
  readonly deviceId: string;
  readonly sessionId: string;
  readonly outcome: TaskOutcome;
  readonly submittedAt: number;
  readonly evidenceIds: readonly string[];
  readonly isAdvisoryOnly: true;
}

/**
 * Preserved contradiction between agent results.
 * INVARIANT: Contradictions are preserved with provenance; never resolved by majority vote.
 */
export interface TaskContradiction {
  readonly contradictionId: string;
  readonly taskId: TaskId;
  readonly taskGroupId: TaskGroupId;
  readonly sessionId: string;
  readonly sourceA: {
    readonly agentId: string;
    readonly resultId: string;
    readonly claim: string;
    readonly outcome: string;
  };
  readonly sourceB: {
    readonly agentId: string;
    readonly resultId: string;
    readonly claim: string;
    readonly outcome: string;
  };
  readonly detectedAt: number;
  readonly discrepancySummary: string;
  readonly resolved: false;
}

/**
 * Supervisory review record.
 * INVARIANT: VERIFIED != OWNER_APPROVED.
 */
export interface TaskReviewState {
  readonly reviewId: string;
  readonly taskId: TaskId;
  readonly reviewedAt: number;
  readonly reviewerType: 'SUPERVISOR' | 'MASTER_OWNER';
  readonly reviewerId: string;
  readonly evidenceBundleId: string;
  readonly reviewDecision: 'VERIFIED' | 'REJECTED' | 'ESCALATED_TO_HUMAN';
  readonly humanGateRequestId?: string;
  readonly ownerApproved: boolean;
  readonly notes?: string;
}

/**
 * Governed Agent Task record.
 */
export interface AgentTask {
  readonly taskId: TaskId;
  readonly groupId: TaskGroupId;
  readonly title: string;
  readonly description: string;
  readonly sessionId: string;
  readonly state: TaskExecutionState;
  readonly dependencies: readonly TaskDependency[];
  readonly requiredCapabilities: readonly string[];
  readonly targetPaths: readonly string[];
  readonly forbiddenPaths: readonly string[];
  readonly assignment?: TaskAssignment;
  readonly result?: AgentTaskResult;
  readonly evidenceBundleId?: string;
  readonly reviewState?: TaskReviewState;
  readonly createdAt: number;
  readonly updatedAt: number;
}

/**
 * Governed Multi-Agent Task Group.
 */
export interface TaskGroup {
  readonly groupId: TaskGroupId;
  readonly title: string;
  readonly description?: string;
  readonly sessionId: string;
  readonly ownerId: string;
  readonly taskIds: readonly TaskId[];
  readonly state: TaskExecutionState;
  readonly createdAt: number;
  readonly updatedAt: number;
}

/**
 * In-memory state representation of the orchestration subsystem.
 */
export interface OrchestrationStateSnapshot {
  readonly groups: readonly TaskGroup[];
  readonly tasks: readonly AgentTask[];
  readonly artifacts: readonly TaskArtifact[];
  readonly evidenceRecords: readonly EvidenceRecord[];
  readonly bundles: readonly EvidenceBundle[];
  readonly contradictions: readonly TaskContradiction[];
  readonly reviews: readonly TaskReviewState[];
}

/**
 * Canonical error codes for orchestration.
 */
export type OrchestrationErrorCode =
  | 'USER_STOP_ACTIVE'
  | 'SECURITY_VIOLATION'
  | 'CROSS_SESSION_ORCHESTRATION_REJECTED'
  | 'TASK_NOT_FOUND'
  | 'TASK_GROUP_NOT_FOUND'
  | 'INVALID_TASK_STATE'
  | 'INVALID_TASK_ASSIGNMENT'
  | 'TARGET_AGENT_NOT_REGISTERED'
  | 'DELEGATION_NOT_FOUND'
  | 'DELEGATION_NOT_ACTIVE'
  | 'DELEGATION_EXPIRED'
  | 'DELEGATION_REVOKED'
  | 'CAPABILITY_NOT_DELEGATED'
  | 'LEASE_NOT_FOUND'
  | 'LEASE_EXPIRED'
  | 'LEASE_REVOKED'
  | 'TASK_DEPENDENCY_UNRESOLVED'
  | 'TASK_DEPENDENCY_FAILED'
  | 'TASK_DEPENDENCY_CYCLE'
  | 'TASK_DEPENDENCY_CROSS_SESSION'
  | 'TASK_DEPENDENCY_INVALID'
  | 'ARTIFACT_INTEGRITY_FAILURE'
  | 'FORBIDDEN_CREDENTIAL_PERSISTENCE'
  | 'EVIDENCE_NOT_FOUND'
  | 'EVIDENCE_INTEGRITY_FAILURE'
  | 'EVIDENCE_VERIFICATION_FAILED'
  | 'SELF_APPROVAL_REJECTED'
  | 'HUMAN_APPROVAL_REQUIRED'
  | 'COLLECTIVE_AUTHORITY_REJECTED';
