// src/core/policyGovernanceReadiness/policyGovernanceReadinessCriteria.ts
// BOWCON V4.0 — MS-1.3.76: GOVERNED POLICY GOVERNANCE PLANE END-TO-END VALIDATION,
// EVIDENCE-BASED READINESS ASSESSMENT & CONDITIONAL PHASE EXIT GATE
//
// Readiness Criteria Specification (Component 856).
// Formally defines the 24 canonical readiness criteria derived from the existing
// architecture specifications, security invariants, and execution plan requirements.
//
// Every newly formalized criterion is explicitly marked:
// derivation: 'DERIVED_FROM_EXISTING_ARCHITECTURE'

import {
  type ReadinessCriterionDefinition,
  createCriterionId,
} from './policyGovernanceReadinessTypes.js';

export const CANONICAL_READINESS_CRITERIA: readonly ReadinessCriterionDefinition[] = Object.freeze([
  {
    criterionId: createCriterionId('CRITERION_01'),
    criterionNumber: 1,
    name: 'GOVERNANCE_COVERAGE',
    description: 'All required Phase 1.3 governance layers (MS-1.3.62 through MS-1.3.75) have concrete operational implementations.',
    isMandatory: true,
    derivation: 'DERIVED_FROM_EXISTING_ARCHITECTURE',
    requiredLayers: [
      'OBSERVABILITY',
      'EVIDENCE_INVESTIGATION',
      'DECISION_PROPOSAL',
      'REMEDIATION_PLANNING',
      'HUMAN_AUTHORIZATION',
      'EXECUTION_DISPATCH',
      'OUTCOME_VERIFICATION',
      'POST_EXECUTION_RECONCILIATION',
      'FEEDBACK_REVIEW',
      'EVOLUTION_PLANNING',
      'CANDIDATE_SYNTHESIS',
      'CANDIDATE_VALIDATION',
      'CANDIDATE_AUTHORIZATION',
      'STAGED_ACTIVATION',
      'RUNTIME_SYNCHRONIZATION',
      'PDP_ENFORCEMENT',
      'PEP_ENFORCEMENT',
      'ROLLBACK_SUNSET_RECOVERY',
      'LIFECYCLE_RECONCILIATION',
      'INCIDENT_RESPONSE',
      'CONTAINMENT_CLEARANCE',
      'RECOVERY_AUTHORIZATION',
      'RECOVERY_VERIFICATION',
      'INCIDENT_RESOLUTION',
      'INCIDENT_CLOSURE',
    ],
    targetInvariants: ['PHASE_1_3_GOVERNANCE_COVERAGE_COMPLETE'],
  },
  {
    criterionId: createCriterionId('CRITERION_02'),
    criterionNumber: 2,
    name: 'GOVERNANCE_SEPARATION',
    description: 'Observation, Evidence, Decision, Authorization, Execution, Verification, Policy Authority, and Policy Mutation remain strictly decoupled.',
    isMandatory: true,
    derivation: 'DERIVED_FROM_EXISTING_ARCHITECTURE',
    requiredLayers: [
      'OBSERVABILITY',
      'EVIDENCE_INVESTIGATION',
      'DECISION_PROPOSAL',
      'HUMAN_AUTHORIZATION',
      'EXECUTION_DISPATCH',
      'OUTCOME_VERIFICATION',
    ],
    targetInvariants: [
      'OBSERVATION != DECISION',
      'DECISION != AUTHORIZATION',
      'AUTHORIZATION != EXECUTION',
      'EXECUTION != VERIFICATION',
      'PDP != POLICY_AUTHORITY',
      'PEP != POLICY_AUTHORITY',
    ],
  },
  {
    criterionId: createCriterionId('CRITERION_03'),
    criterionNumber: 3,
    name: 'HUMAN_AUTHORITY',
    description: 'All policy-authoritative transitions requiring human governance have a non-bypassable human boundary enforcing HUMAN_AUTHORIZATION > AUTONOMOUS_AUTHORIZATION and anti-self-approval.',
    isMandatory: true,
    derivation: 'DERIVED_FROM_EXISTING_ARCHITECTURE',
    requiredLayers: [
      'HUMAN_AUTHORIZATION',
      'CANDIDATE_AUTHORIZATION',
      'STAGED_ACTIVATION',
      'ROLLBACK_SUNSET_RECOVERY',
      'CONTAINMENT_CLEARANCE',
      'RECOVERY_AUTHORIZATION',
      'INCIDENT_CLOSURE',
    ],
    targetInvariants: [
      'HUMAN_AUTHORIZATION > AUTONOMOUS_AUTHORIZATION',
      'ANTI_SELF_APPROVAL',
      'REJECT_AUTONOMOUS_PERSONAS',
    ],
  },
  {
    criterionId: createCriterionId('CRITERION_04'),
    criterionNumber: 4,
    name: 'ZERO_AUTONOMOUS_POLICY_MUTATION',
    description: 'No autonomous execution, model reasoning, background task, or tool dispatch can directly mutate active policy definitions or state.',
    isMandatory: true,
    derivation: 'DERIVED_FROM_EXISTING_ARCHITECTURE',
    requiredLayers: ['STAGED_ACTIVATION', 'RUNTIME_SYNCHRONIZATION', 'ROLLBACK_SUNSET_RECOVERY'],
    targetInvariants: ['ZERO_AUTONOMOUS_POLICY_MUTATION', 'IMMUTABLE_ACTIVE_POLICY_RECORDS'],
  },
  {
    criterionId: createCriterionId('CRITERION_05'),
    criterionNumber: 5,
    name: 'ZERO_AUTONOMOUS_ACTIVATION',
    description: 'Policy activation strictly requires preflight verification and governed human authorization commit in MS-1.3.70.',
    isMandatory: true,
    derivation: 'DERIVED_FROM_EXISTING_ARCHITECTURE',
    requiredLayers: ['CANDIDATE_AUTHORIZATION', 'STAGED_ACTIVATION'],
    targetInvariants: ['ZERO_AUTONOMOUS_POLICY_ACTIVATION', 'STAGED_POLICY != ACTIVE_POLICY'],
  },
  {
    criterionId: createCriterionId('CRITERION_06'),
    criterionNumber: 6,
    name: 'ZERO_AUTONOMOUS_ROLLBACK',
    description: 'Policy rollback, sunset, and recovery require explicit human authority in MS-1.3.72; autonomous repair or self-healing is strictly rejected.',
    isMandatory: true,
    derivation: 'DERIVED_FROM_EXISTING_ARCHITECTURE',
    requiredLayers: ['ROLLBACK_SUNSET_RECOVERY'],
    targetInvariants: ['ZERO_AUTONOMOUS_ROLLBACK', 'ZERO_SELF_HEALING_POLICY'],
  },
  {
    criterionId: createCriterionId('CRITERION_07'),
    criterionNumber: 7,
    name: 'RUNTIME_ENFORCEMENT',
    description: 'Committed ACTIVE_POLICY is deterministically synchronized into runtime snapshot, PDP evaluation, and PEP capability enforcement.',
    isMandatory: true,
    derivation: 'DERIVED_FROM_EXISTING_ARCHITECTURE',
    requiredLayers: ['RUNTIME_SYNCHRONIZATION', 'PDP_ENFORCEMENT', 'PEP_ENFORCEMENT'],
    targetInvariants: ['ACTIVE_POLICY -> RUNTIME_SNAPSHOT -> PDP -> PEP'],
  },
  {
    criterionId: createCriterionId('CRITERION_08'),
    criterionNumber: 8,
    name: 'FAIL_CLOSED_BEHAVIOR',
    description: 'Invalid, stale, corrupted, conflicting, unauthorized, or tampered policy states fail closed with strict denial.',
    isMandatory: true,
    derivation: 'DERIVED_FROM_EXISTING_ARCHITECTURE',
    requiredLayers: [
      'CANDIDATE_VALIDATION',
      'STAGED_ACTIVATION',
      'RUNTIME_SYNCHRONIZATION',
      'LIFECYCLE_RECONCILIATION',
      'INCIDENT_RESPONSE',
    ],
    targetInvariants: ['FAIL_CLOSED', 'CORRUPTION_FAILS_CLOSED'],
  },
  {
    criterionId: createCriterionId('CRITERION_09'),
    criterionNumber: 9,
    name: 'HARD_FORBIDDEN_FLOOR',
    description: 'Canonical hard-forbidden actions (transfer_funds, delete_database, execute_shell, bypass_sandbox, disable_audit, override_kill_switch) can never become permitted.',
    isMandatory: true,
    derivation: 'DERIVED_FROM_EXISTING_ARCHITECTURE',
    requiredLayers: [
      'REMEDIATION_PLANNING',
      'EVOLUTION_PLANNING',
      'CANDIDATE_VALIDATION',
      'PDP_ENFORCEMENT',
      'PEP_ENFORCEMENT',
      'ROLLBACK_SUNSET_RECOVERY',
    ],
    targetInvariants: ['HARD_FORBIDDEN_FLOOR_NON_NEGOTIABLE'],
  },
  {
    criterionId: createCriterionId('CRITERION_10'),
    criterionNumber: 10,
    name: 'USER_STOP',
    description: 'USER_STOP > EVERYTHING across synchronization, activation, rollback, sunset, recovery, incident response, reconciliation, and execution.',
    isMandatory: true,
    derivation: 'DERIVED_FROM_EXISTING_ARCHITECTURE',
    requiredLayers: [
      'STAGED_ACTIVATION',
      'RUNTIME_SYNCHRONIZATION',
      'ROLLBACK_SUNSET_RECOVERY',
      'LIFECYCLE_RECONCILIATION',
      'INCIDENT_RESPONSE',
      'INCIDENT_RESOLUTION',
    ],
    targetInvariants: ['USER_STOP > EVERYTHING'],
  },
  {
    criterionId: createCriterionId('CRITERION_11'),
    criterionNumber: 11,
    name: 'TENANT_ISOLATION',
    description: 'Multi-tenant partitioning strictly isolates policy state, incidents, authorizations, rollbacks, and reconciliations against path traversal, null bytes, and Windows reserved names.',
    isMandatory: true,
    derivation: 'DERIVED_FROM_EXISTING_ARCHITECTURE',
    requiredLayers: [
      'CANDIDATE_AUTHORIZATION',
      'STAGED_ACTIVATION',
      'RUNTIME_SYNCHRONIZATION',
      'ROLLBACK_SUNSET_RECOVERY',
      'LIFECYCLE_RECONCILIATION',
      'INCIDENT_RESPONSE',
      'INCIDENT_RESOLUTION',
    ],
    targetInvariants: ['STRICT_TENANT_PARTITIONING', 'REJECT_PATH_TRAVERSAL'],
  },
  {
    criterionId: createCriterionId('CRITERION_12'),
    criterionNumber: 12,
    name: 'PROVENANCE',
    description: 'Critical governance transitions have tamper-evident, append-only cryptographic SHA-256 hash chains verified across reload.',
    isMandatory: true,
    derivation: 'DERIVED_FROM_EXISTING_ARCHITECTURE',
    requiredLayers: [
      'DECISION_PROPOSAL',
      'FEEDBACK_REVIEW',
      'EVOLUTION_PLANNING',
      'CANDIDATE_AUTHORIZATION',
      'STAGED_ACTIVATION',
      'RUNTIME_SYNCHRONIZATION',
      'ROLLBACK_SUNSET_RECOVERY',
      'LIFECYCLE_RECONCILIATION',
      'INCIDENT_RESPONSE',
      'INCIDENT_RESOLUTION',
    ],
    targetInvariants: ['CRYPTOGRAPHIC_PROVENANCE_INTEGRITY', 'TAMPER_EVIDENT_HASH_CHAINS'],
  },
  {
    criterionId: createCriterionId('CRITERION_13'),
    criterionNumber: 13,
    name: 'AUDITABILITY',
    description: 'All governance events are recorded to globalAuditLedger with secret and diagnostic sanitization via DiagnosisSanitizer.',
    isMandatory: true,
    derivation: 'DERIVED_FROM_EXISTING_ARCHITECTURE',
    requiredLayers: [
      'DECISION_PROPOSAL',
      'EXECUTION_DISPATCH',
      'POST_EXECUTION_RECONCILIATION',
      'FEEDBACK_REVIEW',
      'EVOLUTION_PLANNING',
      'CANDIDATE_AUTHORIZATION',
      'STAGED_ACTIVATION',
      'RUNTIME_SYNCHRONIZATION',
      'ROLLBACK_SUNSET_RECOVERY',
      'LIFECYCLE_RECONCILIATION',
      'INCIDENT_RESPONSE',
      'INCIDENT_RESOLUTION',
    ],
    targetInvariants: ['GLOBAL_AUDIT_LEDGER_EMISSION', 'SECRET_SANITIZATION'],
  },
  {
    criterionId: createCriterionId('CRITERION_14'),
    criterionNumber: 14,
    name: 'POLICY_LIFECYCLE_CONSISTENCY',
    description: 'Activation, runtime snapshot, rollback, sunset, recovery, reconciliation, and incident state cannot silently contradict one another.',
    isMandatory: true,
    derivation: 'DERIVED_FROM_EXISTING_ARCHITECTURE',
    requiredLayers: [
      'STAGED_ACTIVATION',
      'RUNTIME_SYNCHRONIZATION',
      'ROLLBACK_SUNSET_RECOVERY',
      'LIFECYCLE_RECONCILIATION',
    ],
    targetInvariants: ['LIFECYCLE_CONSISTENCY_VERIFIED', 'ZERO_SILENT_DRIFT'],
  },
  {
    criterionId: createCriterionId('CRITERION_15'),
    criterionNumber: 15,
    name: 'INCIDENT_SAFETY',
    description: 'Degradation detection and incident states cannot autonomously mutate, resync, or repair policy definitions.',
    isMandatory: true,
    derivation: 'DERIVED_FROM_EXISTING_ARCHITECTURE',
    requiredLayers: ['INCIDENT_RESPONSE', 'CONTAINMENT_CLEARANCE'],
    targetInvariants: ['INCIDENT_RESPONSE != POLICY_AUTHORITY', 'CONTAINMENT != MUTATION'],
  },
  {
    criterionId: createCriterionId('CRITERION_16'),
    criterionNumber: 16,
    name: 'RECOVERY_SAFETY',
    description: 'Recovery from incidents is separately authorized by human governance and independently verified across runtime, sync, and reconciliation layers.',
    isMandatory: true,
    derivation: 'DERIVED_FROM_EXISTING_ARCHITECTURE',
    requiredLayers: ['RECOVERY_AUTHORIZATION', 'RECOVERY_VERIFICATION', 'ROLLBACK_SUNSET_RECOVERY'],
    targetInvariants: [
      'CONTAINMENT_CLEARANCE != RECOVERY_AUTHORIZATION',
      'RECOVERY_AUTHORIZATION != RECOVERY_EXECUTION',
      'RECOVERY_EXECUTION != RECOVERY_VERIFICATION',
    ],
  },
  {
    criterionId: createCriterionId('CRITERION_17'),
    criterionNumber: 17,
    name: 'INCIDENT_CLOSURE',
    description: 'Resolved incidents cannot be deleted; closure requires human governance authorization distinct from resolution confirmation.',
    isMandatory: true,
    derivation: 'DERIVED_FROM_EXISTING_ARCHITECTURE',
    requiredLayers: ['INCIDENT_RESOLUTION', 'INCIDENT_CLOSURE'],
    targetInvariants: ['INCIDENT_RESOLUTION != INCIDENT_CLOSURE', 'INCIDENT_CLOSURE != INCIDENT_DELETION'],
  },
  {
    criterionId: createCriterionId('CRITERION_18'),
    criterionNumber: 18,
    name: 'NO_AUTHORITY_DUPLICATION',
    description: 'No later milestone has created an alternate policy-authority path; MS-1.3.70 remains the sole activation authority, MS-1.3.72 the sole rollback/recovery execution authority, and MS-1.3.74/75 the sole incident authorities.',
    isMandatory: true,
    derivation: 'DERIVED_FROM_EXISTING_ARCHITECTURE',
    requiredLayers: ['STAGED_ACTIVATION', 'ROLLBACK_SUNSET_RECOVERY', 'INCIDENT_RESPONSE', 'INCIDENT_RESOLUTION'],
    targetInvariants: ['SINGLE_CANONICAL_AUTHORITY_SURFACE', 'ZERO_DUPLICATE_AUTHORITY'],
  },
  {
    criterionId: createCriterionId('CRITERION_19'),
    criterionNumber: 19,
    name: 'INTEGRATION_REALITY',
    description: 'Critical governance components are not merely REAL in the component matrix; they participate in end-to-end executable paths.',
    isMandatory: true,
    derivation: 'DERIVED_FROM_EXISTING_ARCHITECTURE',
    requiredLayers: [
      'DECISION_PROPOSAL',
      'HUMAN_AUTHORIZATION',
      'EXECUTION_DISPATCH',
      'CANDIDATE_AUTHORIZATION',
      'STAGED_ACTIVATION',
      'RUNTIME_SYNCHRONIZATION',
      'PDP_ENFORCEMENT',
      'PEP_ENFORCEMENT',
      'ROLLBACK_SUNSET_RECOVERY',
      'LIFECYCLE_RECONCILIATION',
      'INCIDENT_RESPONSE',
      'INCIDENT_RESOLUTION',
    ],
    targetInvariants: ['EXECUTABLE_INTEGRATION_PATH_VERIFIED'],
  },
  {
    criterionId: createCriterionId('CRITERION_20'),
    criterionNumber: 20,
    name: 'REGRESSION_INTEGRITY',
    description: 'All existing regression test suites across all prior milestones pass 100% without weakening assertions or modifying expected behavior.',
    isMandatory: true,
    derivation: 'DERIVED_FROM_EXISTING_ARCHITECTURE',
    requiredLayers: ['OBSERVABILITY', 'INCIDENT_RESOLUTION'],
    targetInvariants: ['FULL_REGRESSION_100_PERCENT_PASS'],
  },
  {
    criterionId: createCriterionId('CRITERION_21'),
    criterionNumber: 21,
    name: 'BUILD_INTEGRITY',
    description: 'TypeScript typechecking (npm run typecheck) and production build (npm run build) compile with clean 0 errors.',
    isMandatory: true,
    derivation: 'DERIVED_FROM_EXISTING_ARCHITECTURE',
    requiredLayers: ['OBSERVABILITY', 'INCIDENT_RESOLUTION'],
    targetInvariants: ['CLEAN_TYPECHECK_AND_BUILD'],
  },
  {
    criterionId: createCriterionId('CRITERION_22'),
    criterionNumber: 22,
    name: 'SECURITY_INTEGRITY',
    description: 'Forbidden process execution primitives (child_process, exec, spawn, eval) and authority leakage keywords are completely absent from governance domains.',
    isMandatory: true,
    derivation: 'DERIVED_FROM_EXISTING_ARCHITECTURE',
    requiredLayers: ['OBSERVABILITY', 'INCIDENT_RESOLUTION'],
    targetInvariants: ['ZERO_FORBIDDEN_PRIMITIVES', 'ZERO_AUTHORITY_LEAKAGE'],
  },
  {
    criterionId: createCriterionId('CRITERION_23'),
    criterionNumber: 23,
    name: 'PROTECTED_WORKSPACE',
    description: 'The external protected workspace C:\\BOW\\shopofbow remains 100% untouched (Test-Path returns False).',
    isMandatory: true,
    derivation: 'DERIVED_FROM_EXISTING_ARCHITECTURE',
    requiredLayers: ['OBSERVABILITY', 'INCIDENT_RESOLUTION'],
    targetInvariants: ['PROTECTED_WORKSPACE_UNTOUCHED'],
  },
  {
    criterionId: createCriterionId('CRITERION_24'),
    criterionNumber: 24,
    name: 'NO_UNVERIFIED_CLAIMS',
    description: 'Every PASS criterion references concrete repository evidence and executable verification; UNKNOWN, PARTIAL, or NOT_TESTED never converts to PASS.',
    isMandatory: true,
    derivation: 'DERIVED_FROM_EXISTING_ARCHITECTURE',
    requiredLayers: ['OBSERVABILITY', 'INCIDENT_RESOLUTION'],
    targetInvariants: ['EVIDENCE_BASED_VERIFICATION_ONLY', 'ZERO_UNVERIFIED_CLAIMS'],
  },
]);

export function getCriterionById(criterionId: string): ReadinessCriterionDefinition | undefined {
  return CANONICAL_READINESS_CRITERIA.find(c => c.criterionId === criterionId);
}
